CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = yes
DYNAMICT_TAPPING_TERM_ENABLE = yes
LEADER_ENABLE = yes
UNICODEMAP_ENABLE = yes

SRC += features/color_layer.c

# EXTRAFLAGS += -DDEBUG_ACTION
